name: build-main
run-name: build-main
on:
  push:
    branches:
      - main
  schedule:
    # every day at midnight
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: scrape and store dates
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - run: pip install -r requirements.txt

      # downloads and unzips a lot of datasets
      - run: ./setup.sh

      - run: python3 analyze_frequency.py

      # - run: python3 check_dates.py

      # - run: python3 track_static.py

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5